#spring:
#  application:
#    name: system-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/system?serverTimezone=UTC&userUnicode=true&useSSL=false&
#    username: root
#    password: 332129702
spring:
  application:
    name: system-service
  cloud:
    nacos:
      server-addr: 192.168.43.156:8848
      config:
        namespace: dev
        group: ulearn
        file-extension: yaml
        refresh-enabled: true

  #profiles默认为dev
  profiles:
    active: dev